# Generated by Django 4.2.1 on 2023-08-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopkart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCreationForm',
            new_name='MyUserCreationForm',
        ),
    ]
