# Generated by Django 4.2.1 on 2023-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopkart', '0002_rename_usercreationform_myusercreationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=250, null=True)),
                ('school_id', models.IntegerField(null=True)),
                ('school_location', models.CharField(max_length=250, null=True)),
                ('school_level', models.IntegerField(null=True)),
                ('school_auth', models.BooleanField(null=True)),
            ],
        ),
    ]
