# Generated by Django 4.2.1 on 2023-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopkart', '0004_course_staff_subject_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fromform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=140, null=True)),
                ('user_surname', models.CharField(max_length=140, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_3',
        ),
    ]
