# Generated by Django 4.2.1 on 2023-08-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopkart', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='surname',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
