# Generated by Django 4.2.1 on 2023-10-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('userSurname', models.CharField(max_length=150)),
                ('userContact', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=254)),
                ('DoB', models.DateField()),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Uttrakhand', 'Uttrakhand')], max_length=150)),
                ('pincode', models.PositiveIntegerField()),
                ('profileImage', models.ImageField(blank=True, upload_to='ProfileGallery')),
                ('resumeHoleder', models.FileField(blank=True, upload_to='ResumeFolder')),
            ],
        ),
    ]
