# Generated by Django 4.2.1 on 2023-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Surname', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=150)),
                ('Mobile_number', models.IntegerField()),
                ('Password', models.CharField(max_length=150)),
                ('Confirm_password', models.CharField(max_length=150)),
                ('Answer', models.CharField(max_length=350)),
            ],
        ),
    ]
