# Generated by Django 4.2.1 on 2023-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AddField(
            model_name='signup',
            name='Emergency_options',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='signup',
            name='Image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
