# Generated by Django 4.2.6 on 2023-10-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(choices=[('Wedding', 'Wedding'), ('Politics', 'Politics'), ('Climate', 'Climate'), ('Tourism', 'Toursim'), ('Employement', 'Employement'), ('History', 'History')], max_length=200)),
                ('Description', models.TextField()),
                ('Category_image', models.ImageField(upload_to='CategoryImage')),
                ('Category_url', models.CharField(max_length=150)),
                ('Category_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('Post_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=350)),
                ('Post_content', models.TextField()),
                ('Post_url', models.CharField(max_length=200)),
                ('Post_image', models.ImageField(upload_to='PostImage')),
                ('Post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Post_category_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.category')),
            ],
        ),
    ]
