# Generated by Django 4.2.6 on 2023-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogtitles_remove_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Writer_name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
